### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by reviewher** [theatre-js/theatre#305]
The main LICENSE file and the github sidebar say the repo is [Apache-2.0 license](https://github.com/theatre-js/theatre/blob/main/LICENSE)

[But there is AGPL code in the repo](https://github.com/theatre-js/theatre/blob/main/theatre/studio/LICENSE)

It is not at all clear from first blush that the repo contains AGPL code.  Is the AGPL licensing a mistake or is the project license file in error?

**Comment by reviewher** [comment]
The confusion is obvious if you look at the repo:

<img width="273" alt="Screen Shot 2022-09-26 at 2 44 06 PM" src="https://user-images.githubusercontent.com/24845478/192355685-d3fdd834-fbe8-483e-806b-d6bd0e6eba55.png">

This is factually incorrect according to the README.  The LICENSE file should be updated to reflect this nuance, otherwise you are (intentionally?) misrepresenting the project license as understood by the tooling and general ecosystem

**Comment by vezwork** [comment]
I talked with @AndrewPrifer and @AriaMinaei a bit about this.

We expose the Apache 2.0 license at the top as it covers the majority of the paths in the monorepo, including @theatre/core, which is the package that the _overwhelming majority_ of people using Theatre.js will end up with in their production code. Not doing so would be more confusing in our opinion because people would have a harder time seeing the most relevant license at a glance. We make it clear just half a page down in the standard License section of the README that we have AGPL licensed code in the repo.

That said, I do understand that seeing Apache 2.0 in the sidebar, and then discovering that it is in fact not the only license in the repo can be frustrating at first sight. I wish GitHub allowed to indicate this nuance more clearly!

We do clearly indicate the licensing in the README and in the LICENSE.

Repos of all kinds often contain material with different licensing. It is common practice to expose a "main" license at the top, otherwise you wouldn't be able to indicate a license which applies to most people. This is exactly _why READMEs as a convention include a License heading, under which the licensing is clarified for the different parts of the repo_.

We provide all packages that have a different license with their own LICENSE file at their subpath, which all tooling in the NPM/monorepo ecosystem should prioritize when determining licensing. @theatre/studio clearly shows up as AGPL on NPM too.

I hope this clears up somewhat why we chose this convention to indicate our licensing, and if you have any other questions, I'd be glad to answer them!

**Comment by reviewher** [comment]
The honest thing to do is to note which parts are AGPL and which parts are Apache 2 in the license file.  Many projects mix licenses, like Strapi: https://github.com/strapi/strapi/blob/main/LICENSE

> * All software that resides under an "ee/" directory (the “EE Software”), if that directory exists, is licensed under the license defined in "ee/LICENSE".

> * All software outside of the above-mentioned directories or restrictions above is available under the "MIT Expat" license as set forth below.

If the goal is to make this project appear to be completely Apache 2.0, the honest thing to do is to move the AGPL bits into a separate repo that can be marked as AGPL.  Otherwise it looks like an attempt to deceive the community.
