### ISSUE TITLE
Internal state is not updated when an object is detached from a sheet

### ISSUE THREAD

**Issue by glegenty** [theatre-js/theatre#421]
Hello,
It seems that the internal state is not updated when we detach an object from the sheet, only the studio UI is updated.
The detached object persist in the local storage too.
Is it intentional ? Is there something that i can do to update the state according to this event ?
Thank you

**Comment by AriaMinaei** [comment]
This is actually intentional. Detaching is supposed to be different from deleting the overrides of an object. Imagine if the scene is a ppt-style slideshow. You're viewing the first slide, and when you switch over to the second slide, the objects from the first one get detached. Once you switch back to Slide 1, they get re-created again, and their overrides are intact.

If you want the overrides to be deleted as well, you should run a transaction before detaching:

```
studio.transaction(({unset}) => unset(object.props))
```

**Comment by themancalledjakob** [comment]
perhaps of interest: https://github.com/theatre-js/theatre/pull/393

for me, unset clears the objects props entirely, but it still remains in localStorage
